### ISSUE TITLE
Adcionar tela mostradno uma postagem e seus comentario

### ISSUE THREAD

**Issue by psmousinho** [psmousinho/TheCuckoo#3]

**Comment by DefinitelyNotACactus** [comment]
>As postagens dos usuários contêm um texto e uma foto opcional. No texto é possível marcar outros usuários escrevendo-se cada nome de usuário precedido do caractere @, por exemplo, @fulano. Também é possível marcar a postagem com ​vários tópicos​, precedendo-o com o caractere #, por exemplo #incrível; o nome do tópico segue a mesma regra de composição dos nomes de usuários. Cada postagem pode possuir comentários de texto, que também podem conter marcações de usuários e tópicos. Os comentários de uma postagem são exibidos do mais antigo para o mais recente. Uma pessoa pode apagar suas postagens, seus comentários em qualquer postagem e comentários de outras pessoas em suas postagens.
