### ISSUE TITLE
Habilidade dde modificar a visibilidaded do perfil

### ISSUE THREAD

**Issue by psmousinho** [psmousinho/TheCuckoo#6]

**Comment by DefinitelyNotACactus** [comment]
>Os perfis podem ser públicos ou privados. Quando um perfil é público, ao ser visitado, qualquer usuário pode visualizar o nome do usuário, o nome real, a biografia e as postagens, da mais recente para a mais antiga. Quando é privado, as postagens, seguidores e seguidos são exibidas apenas para os seguidores.
