### ISSUE TITLE
implementar/ melhorar Sistema de notificação

### ISSUE THREAD

**Issue by psmousinho** [psmousinho/TheCuckoo#7]

**Comment by DefinitelyNotACactus** [comment]
>Existe uma central de notificações que concentra os eventos de interesse do usuário. Se o perfil do usuário for público, cada novo seguidor gera uma notificação, que lhe permite visitar o perfil do novo seguidor. Se o perfil for privado, a notificação permite aceitar ou recusar o seguidor. Se o usuário aceitar a solicitação, é enviada uma notificação ao novo seguidor com esta informação. Quando um usuário é marcado em uma postagem ou comentário, ele recebe uma notificação se o perfil onde ocorreu a marcação é público ou é seguido por ele. A notificação informa qual usuário lhe marcou e em qual perfil ele foi marcado. A partir da notificação, o usuário pode acessar diretamente a postagem onde foi marcado. As notificações são exibidas da mais recente para a mais antiga.

**Comment by psmousinho** [comment]
Se o usuário aceitar a solicitação, é enviada uma notificação ao novo seguidor com esta informação.

**Comment by DefinitelyNotACactus** [comment]
>Existe uma central de notificações que concentra os eventos de interesse do usuário. Se o perfil do usuário for público, cada novo seguidor gera uma notificação, que lhe permite visitar o perfil do novo seguidor. Se o perfil for privado, a notificação permite aceitar ou recusar o seguidor. Se o usuário aceitar a solicitação, é enviada uma notificação ao novo seguidor com esta informação.

Implementado.
