### ISSUE TITLE
Sistema de bloqueio

### ISSUE THREAD

**Issue by psmousinho** [psmousinho/TheCuckoo#8]

**Comment by DefinitelyNotACactus** [comment]
>Uma pessoa pode bloquear outra, bloqueador e bloqueado, respectivamente. Se ocorre um bloqueio, tudo o que o bloqueado postou no perfil do bloqueador é apagado, e vice-versa. Comentários feitos pelo bloqueado em perfis diferentes do bloqueador não são apagados, porém o bloqueador não irá vê-los ao visitar a postagem, e vice-versa. Caso o bloqueado seja marcado por outrem em postagem ou comentário, esta mensagem continua sendo visível ao bloqueador, e vice-versa. ​Quaisquer seguimentos entre os usuários envolvidos no bloqueio são desfeitos​. Um usuário pode desbloquear outro, mas os dados apagados remanescem apagados.

**Comment by DefinitelyNotACactus** [comment]
Apagar comentários e seguimento entre bloqueado/bloqueador foi implementado.
TODO: Visibilidade de comentários

**Comment by DefinitelyNotACactus** [comment]
Concluído
