### ISSUE TITLE
Busca por topico

### ISSUE THREAD

**Issue by psmousinho** [psmousinho/TheCuckoo#9]

**Comment by DefinitelyNotACactus** [comment]
> Por fim, é possível fazer busca por um tópico e por usuário. A busca por usuário deve vasculhar pelos nomes de usuários, nomes reais e biografias. O resultado da busca por tópicos é do mais recente para o mais antigo, enquanto que o resultado da busca por usuário é do com o maior número de seguidores para o com menor quantidade.
